- type: job
  id: TownSheriff
  setPreference: true
  name: job-name-townsheriff
  description: job-description-townsheriff
  playTimeTracker: TownSheriff
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Townsfolk
      min: 18000 # 5 hours
  startingGear: TownSheriffGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk
  access:
  - TownieLaw
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Townsfolk

- type: playTimeTracker
  id: TownSheriff
