- type: job
  id: BoSMidScribe
  setPreference: true
  name: job-name-bos-mid-scribe
  description: job-description-bos-mid-scribe
  playTimeTracker: BoSMidScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodMidwest
      min: 18000 # 5 hours
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
            - Ghoul
  startingGear: BoSMidScribeGear
  alwaysUseSpawner: true
  icon: "JobIconBosMScriptor" # Corvax-Change
  supervisors: job-supervisors-bos-mid
  access:
  - BoSMidwest
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodMidwest
      - type: CPRTraining

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSScribe
    back: N14ClothingBackpackSatchelMilitary # Corvax-Change
    shoes: N14ClothingBootsLeather
    pocket1: NCRBoSMidwestScribekits
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSMidwest
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSMidScribe
