- type: job
  id: NCRMedic
  setPreference: true
  name: job-name-ncr-medic
  description: job-description-ncr-medic
  playTimeTracker: NCRDoctor
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 3600 # 1 hour
  startingGear: NCRMedicGear
  icon: "JobIconNcrMedic" # Corvax-Change
  supervisors: job-supervisors-ncr
  canBeAntag: false
  alwaysUseSpawner: true
  access:
  - NCR
  - NCRMedic
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - NCR
      - type: CPRTraining

- type: startingGear
  id: NCRMedicGear
  equipment:
    jumpsuit: N14ClothingUniformNCRDesert # Corvax-Change
    back: N14ClothingBackpackNCR # Corvax-Change
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDNCRDogtagDoctor
    pocket2: NCRmedicloadoutkits
  innerClothingSkirt: N14ClothingUniformNCRDesert # Corvax-Change
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCRDoctor
