- type: job
  id: NCRCadet
  setPreference: true
  name: job-name-ncr-cadet
  description: job-description-ncr-cadet
  playTimeTracker: NCRCadet
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterOverallTimeRequirement
      min: 3600
  startingGear: NCRCadetGear
  icon: "JobIconNcrCadet" # Corvax-Change
  supervisors: job-supervisors-ncr
  canBeAntag: false
  alwaysUseSpawner: true
  access:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - NCR

- type: startingGear
  id: NCRCadetGear
  equipment:
    head: N14ClothingHeadHatNCRSidecap
    back: N14ClothingBackpackNCR # Corvax-Change
    jumpsuit: N14ClothingUniformNCRDesert # Corvax-Change
    shoes: N14ClothingBootsLeatherFilled
    pocket1: NCRcadetloadoutkits
    id: N14IDNCRDogtag
  innerClothingSkirt: N14ClothingUniformNCRDesert # Corvax-Change
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCRCadet
