- type: job
  id: WastelandChaplain
  setPreference: true
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: WastelandChaplain
  startingGear: WastelandChaplainGear
  icon: "JobIconWastelandChaplain" # Corvax-Change
  supervisors: job-supervisors-wastelander
  access:
  - WastelandChaplain
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: WastelandChaplainGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitFollowers
    back: N14ClothingBackpackTrekker # Corvax-Change
    shoes: N14ClothingBootsBlack
  innerClothingSkirt: N14ClothingUniformJumpsuitFollowers
  satchel: N14ClothingBackpackSatchelChaplainFilled
  duffelbag: N14ClothingBackpackDuffelChaplainFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander
    - Bible

- type: playTimeTracker
  id: WastelandChaplain
