- type: job
  id: Wastelander
  setPreference: true
  name: job-name-wastelander
  description: job-description-wastelander
  playTimeTracker: Wastelander
  startingGear: WastelanderGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-wastelander

- type: startingGear
  id: WastelanderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    back: N14ClothingBackpackExplorer # Corvax-Change
    shoes: N14ClothingShoesRags
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander

- type: playTimeTracker
  id: Wastelander
