- type: job
  id: CaesarLegionLegionnaireVeteran
  setPreference: true
  name: job-name-caesar-legion-legionnaire-veteran
  description: job-description-caesar-legionnaire-veteran
  playTimeTracker: CaesarLegionLegionnaireVeteran
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: CaesarLegion
    min: 18000 # 5 hours
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterSexRequirement
    sex: Male
  - !type:CharacterGenderRequirement
    gender: Male
  startingGear: CaesarLegionLegionnaireVeteranGear
  alwaysUseSpawner: true
  icon: "JobIconLegioner"
  supervisors: job-name-caesar-legion-other
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
      - type: ReplacementAccent
        accent: latin

- type: startingGear
  id: CaesarLegionLegionnaireVeteranGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    neck: ClothingNeckRedScarf
    eyes: N14ClothingEyesGlassesWelding
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsBlack
    head: N14ClothingHeadHatBaseballHelmet
    gloves: N14ClothingHandsGlovesTribal
    pocket1: LegionVeteranloadoutkits
    id: N14IDLegionaryMedalSilver2
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther

- type: playTimeTracker
  id: CaesarLegionLegionnaireVeteran
