# MARK: Ranger
- type: loadout
  id: LoadoutNCRRangerVest
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerVest

- type: loadout
  id: LoadoutNCRRangerArmorB
  category: Roles
  cost: 6
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerArmorB

- type: loadout
  id: LoadoutNCRRangerDuster
  category: Roles
  cost: 8
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerDuster

- type: loadout
  id: LoadoutNCRhelmet
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmet

- type: loadout
  id: LoadoutNCRmaskBroken
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerBroken

- type: loadout
  id: LoadoutNCRmaskCombat
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasCombat

#MARK: Corvax-Add

- type: loadout
  id: LoadoutNCRRangerCoat
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerCoat

- type: loadout
  id: LoadoutNCRuniformMaskDesertR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerDesert

- type: loadout
  id: LoadoutNCRuniformMaskOldR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerOld

- type: loadout
  id: LoadoutNCRuniformMaskPriceR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerPrice

- type: loadout
  id: LoadoutNCRuniformMaskEliteR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerElite

- type: loadout
  id: LoadoutNCRuniformMaskModifR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerModif

- type: loadout
  id: LoadoutNCRuniformMaskWeatheredR
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRangerWeathered

- type: loadout
  id: LoadoutNCRDesertHelmetR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetDesert

- type: loadout
  id: LoadoutNCROldHelmetR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetOld

- type: loadout
  id: LoadoutNCRPriceHelmetR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetPrice

- type: loadout
  id: LoadoutNCRFoxHelmetR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetFox

- type: loadout
  id: LoadoutNCRModifHelmetR
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmetModif

- type: loadout
  id: LoadoutNCRNeckCloakRanger
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingNeckCloakRanger


# MARK: Ranger + Vet

- type: loadout
  id: LoadoutNCRhatB
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerB

- type: loadout
  id: LoadoutNCRhatBeret
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatNCRBeretRecon

- type: loadout
  id: LoadoutNCRmaskDesert
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingMaskDesertMask

- type: loadout
  id: LoadoutNCRuniformV1
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV1

- type: loadout
  id: LoadoutNCRuniformV2
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV2

- type: loadout
  id: LoadoutNCRuniformV3
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerV3

- type: loadout
  id: LoadoutNCRuniformPants
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPants

- type: loadout
  id: LoadoutNCRuniformDesertPantsFull
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformDesertPantsFull

- type: loadout
  id: LoadoutNCRgloves
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingHandsGlovesNCR

# misc
- type: loadout
  id: LoadoutNCRRangerMedkit
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14MedkitCombatFilled

# MARK: Corvax-Add

- type: loadout
  id: LoadoutNCRuniformRed
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteranRed

- type: loadout
  id: LoadoutNCRuniformVeteran
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteran

- type: loadout
  id: LoadoutNCRuniformBlack
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerVeteranBlack

- type: loadout
  id: LoadoutNCRuniformBlue
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerBlue

- type: loadout
  id: LoadoutNCRuniformModif
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - N14ClothingUniformRangerModif

- type: loadout
  id: LoadoutNCRClothingNeckOldMantle
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRanger
        - NCRRangerVeteran
  items:
    - ClothingNeckOldMantle

# MARK: Ranger Vet

- type: loadout
  id: LoadoutNCRuniformHelmetDesert
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetDesert

- type: loadout
  id: LoadoutNCRuniformMaskDesert
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRangerDesert

- type: loadout
  id: LoadoutNCRuniformCombatDesert 
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerCombatDesert

- type: loadout
  id: LoadoutNCRRangerEliteOld
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingOuterRangerEliteOld

- type: loadout
  id: LoadoutNCRRangerHelmetEliteOld
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - N14ClothingHeadHatRangerHelmetEliteOld

# MARK: Corvax-Add

- type: loadout
  id: LoadoutNCRuniformMaskEliteVR
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
    - !type:CharacterPlaytimeRequirement
      tracker: NCRRangerVeteran
      min: 216000 # 60 hours veterancy unlock "First Tour"
  items:
    - ClothingMaskGasRangerElite

- type: loadout
  id: LoadoutNCRuniformMaskPriceVR
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRangerPrice

- type: loadout
  id: LoadoutNCRuniformMaskModifVR
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - ClothingMaskGasRangerModif

- type: loadout
  id: LoadoutNCRuniformHelmetFoxVR
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetFox

- type: loadout
  id: LoadoutNCRuniformHelmetPriceVR
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetPrice

- type: loadout
  id: LoadoutNCRuniformHelmetModifVR
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmetModif

- type: loadout
  id: LoadoutNCRuniformHelmetVR
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingHeadHatRangerHelmet

- type: loadout
  id: LoadoutNCRuniformWeathered
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerWeathered

- type: loadout
  id: LoadoutNCRuniformFox
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerFox

- type: loadout
  id: LoadoutNCRuniformPrice
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingOuterRangerPrice

- type: loadout
  id: LoadoutNCRNeckCloakRangerPoncho
  category: Roles
  cost: 1
  exclusive: true
  requirements:
    - !type:CharacterJobRequirement
      jobs:
        - NCRRangerVeteran
  items:
    - N14ClothingNeckCloakRangerPoncho