// using Content.Client.UserInterface.Controls;
// using Content.Shared._NC.DoorLock;
// using Robust.Client.AutoGenerated;
// using Robust.Client.UserInterface.XAML;

// namespace Content.Client._NC.DoorLock;

// [GenerateTypedNameReferences]
// public sealed partial class DoorLockWindow : FancyWindow
// {
//     public event Action<bool>? OpenClose;
//     public event Action<string>? OnCodeChanged;

//     public DoorLockWindow()
//     {
//         RobustXamlLoader.Load(this);
//         IoCManager.InjectDependencies(this);

//         OpenCloseButton.OnPressed += args => OpenClose?.Invoke(args.Button.Pressed);
//         CodeInput.OnTextChanged += args => OnCodeChanged?.Invoke(args.Text);
//     }

//     public void UpdateState(DoorLockBoundUIState state)
//     {
//         OpenCloseButton.Disabled = state.IsLocked;
//     }
// }
